import asyncio
import json
import base64
import re
import os
import time
import aiohttp
import logging
from datetime import datetime, timezone
from nio import (
    AsyncClient, RoomMessageText, RoomMessageImage, RoomMessageFile,
    RoomMessageVideo, RoomMemberEvent, InviteEvent, LoginResponse,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

MATRIX_HOMESERVER = os.environ["MATRIX_HOMESERVER"]
MATRIX_USER_ID    = os.environ["MATRIX_USER_ID"]
MATRIX_TOKEN      = os.environ["MATRIX_TOKEN"]
OWNER_USER_ID     = os.environ["OWNER_USER_ID"]
GITHUB_TOKEN      = os.environ["GITHUB_TOKEN"]
GITHUB_REPO       = os.environ.get("GITHUB_REPO", "Hackatoan/hackatoa.com")
GITHUB_BRANCH     = os.environ.get("GITHUB_BRANCH", "Main")

GITHUB_API = "https://api.github.com"

# ── State machine ────────────────────────────────────────────────────────────
# state[room_id] = {
#   "mode": "idle" | "blog_body" | "mushroom_image",
#   "data": { "title": ..., "date": ..., ... }
# }
state: dict = {}

# ── GitHub helpers ───────────────────────────────────────────────────────────
GH_HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json",
}

async def gh_get_file(session: aiohttp.ClientSession, path: str) -> tuple[str, str]:
    """Returns (decoded_content, sha)."""
    url = f"{GITHUB_API}/repos/{GITHUB_REPO}/contents/{path}?ref={GITHUB_BRANCH}"
    async with session.get(url, headers=GH_HEADERS) as r:
        r.raise_for_status()
        d = await r.json()
        return base64.b64decode(d["content"]).decode(), d["sha"]

async def gh_put_file(session: aiohttp.ClientSession, path: str, content: str, sha: str, message: str):
    url = f"{GITHUB_API}/repos/{GITHUB_REPO}/contents/{path}"
    body = {
        "message": message,
        "content": base64.b64encode(content.encode()).decode(),
        "sha": sha,
        "branch": GITHUB_BRANCH,
    }
    async with session.put(url, headers=GH_HEADERS, json=body) as r:
        r.raise_for_status()

async def gh_put_binary(session: aiohttp.ClientSession, path: str, data: bytes, message: str):
    """Create a new file (no sha needed) or overwrite."""
    url = f"{GITHUB_API}/repos/{GITHUB_REPO}/contents/{path}"
    # Check if file exists to get sha
    sha = None
    async with session.get(url + f"?ref={GITHUB_BRANCH}", headers=GH_HEADERS) as r:
        if r.status == 200:
            d = await r.json()
            sha = d["sha"]
    body = {
        "message": message,
        "content": base64.b64encode(data).decode(),
        "branch": GITHUB_BRANCH,
    }
    if sha:
        body["sha"] = sha
    async with session.put(url, headers=GH_HEADERS, json=body) as r:
        r.raise_for_status()

# ── Blog helpers ─────────────────────────────────────────────────────────────
def slugify(title: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:40]

def parse_blog_entries(js_src: str) -> list:
    m = re.search(r"window\.BLOG_ENTRIES\s*=\s*(\[.*?\]);", js_src, re.DOTALL)
    if not m:
        return []
    return json.loads(m.group(1))

def render_blog_js(entries: list) -> str:
    return "// Auto-generated by Hackatoa CMS\nwindow.BLOG_ENTRIES = " + json.dumps(entries, indent=4) + ";\n"

async def add_blog_post(title: str, body: str) -> str:
    today = datetime.now(timezone.utc)
    date_str = today.strftime("%-m/%-d/%Y, %-I:%M:%S %p")
    meta = f"Log · {today.strftime('%Y-%m-%d')}"
    slug = slugify(title)
    entry = {
        "id": slug,
        "title": title,
        "meta": meta,
        "body": f"{body}\n\n*Posted on {date_str}*",
    }
    async with aiohttp.ClientSession() as sess:
        src, sha = await gh_get_file(sess, "public/blog-data.js")
        entries = parse_blog_entries(src)
        # Ensure unique id
        existing_ids = {e["id"] for e in entries}
        uid = slug
        counter = 1
        while uid in existing_ids:
            uid = f"{slug}-{counter}"
            counter += 1
        entry["id"] = uid
        entries.insert(0, entry)
        new_src = render_blog_js(entries)
        await gh_put_file(sess, "public/blog-data.js", new_src, sha,
                          f"cms: add blog post '{title}'")
    return uid

# ── Mushroom helpers ─────────────────────────────────────────────────────────
def parse_mushrooms(js_src: str) -> list:
    m = re.search(r"window\.MUSHROOMS_DATA\s*=\s*(\[.*?\]);", js_src, re.DOTALL)
    if not m:
        return []
    return json.loads(m.group(1))

def render_mushrooms_js(entries: list) -> str:
    lines = ["// Auto-generated by Hackatoa CMS", "window.MUSHROOMS_DATA = ["]
    for e in entries:
        lines.append("    {")
        for k, v in e.items():
            lines.append(f"        {k}: {json.dumps(v)},")
        lines.append("    },")
    lines.append("];\n")
    return "\n".join(lines)

async def add_mushroom_photo(image_data: bytes, filename: str, title: str | None, meta_date: str | None) -> str:
    today = datetime.now(timezone.utc)
    if not meta_date:
        meta_date = today.strftime("%Y-%m-%d")
    if not title:
        title = f"Mushroom Log {today.strftime('%Y-%m-%d')}"
    gh_path = f"public/assets/mycology/{filename}"
    entry = {
        "image": f"assets/mycology/{filename}",
        "alt": title,
        "title": title,
        "meta": meta_date,
    }
    async with aiohttp.ClientSession() as sess:
        # Upload image
        await gh_put_binary(sess, gh_path, image_data, f"cms: add mushroom photo {filename}")
        # Update mushrooms-data.js
        src, sha = await gh_get_file(sess, "public/mushrooms-data.js")
        entries = parse_mushrooms(src)
        entries.insert(0, entry)
        new_src = render_mushrooms_js(entries)
        await gh_put_file(sess, "public/mushrooms-data.js", new_src, sha,
                          f"cms: add mushroom photo '{title}'")
    return gh_path

# ── Matrix download helper ───────────────────────────────────────────────────
async def download_mxc(client: AsyncClient, mxc_url: str) -> bytes:
    # mxc://server/media_id  ->  /_matrix/media/v3/download/server/media_id
    mxc = mxc_url.removeprefix("mxc://")
    url = f"{MATRIX_HOMESERVER}/_matrix/media/v3/download/{mxc}"
    async with aiohttp.ClientSession() as sess:
        headers = {"Authorization": f"Bearer {client.access_token}"}
        async with sess.get(url, headers=headers) as r:
            r.raise_for_status()
            return await r.read()

# ── Bot send helper ──────────────────────────────────────────────────────────
async def send(client: AsyncClient, room_id: str, text: str):
    await client.room_send(room_id, "m.room.message",
                           {"msgtype": "m.text", "body": text})

HELP_TEXT = """\
📋 Hackatoa CMS Bot — commands:

  !blog <title>     Start a new blog post (sends next message as body)
  !mushroom [title] Add a mushroom photo (send image/file next)
  !status           Show bot status
  !help             This message
"""

# ── Event handlers ───────────────────────────────────────────────────────────
async def on_invite(room: any, event: InviteEvent, client: AsyncClient):
    if event.sender == OWNER_USER_ID:
        log.info(f"Accepting invite to {room.room_id}")
        await client.join(room.room_id)

async def on_text(room, event: RoomMessageText, client: AsyncClient):
    if event.sender == MATRIX_USER_ID:
        return  # ignore own messages
    if event.sender != OWNER_USER_ID:
        return  # only respond to owner

    room_id = room.room_id
    text = event.body.strip()
    room_state = state.get(room_id, {"mode": "idle", "data": {}})

    # ── Handle pending blog body ──────────────────────────────────────────
    if room_state["mode"] == "blog_body":
        if text.startswith("!cancel"):
            state[room_id] = {"mode": "idle", "data": {}}
            await send(client, room_id, "❌ Cancelled.")
            return
        title = room_state["data"]["title"]
        await send(client, room_id, f"⏳ Publishing blog post '{title}'…")
        try:
            slug = await add_blog_post(title, text)
            state[room_id] = {"mode": "idle", "data": {}}
            await send(client, room_id, f"✅ Blog post published! ID: `{slug}`\nhttps://hackatoa.com/#blog")
        except Exception as e:
            log.error(f"Blog post failed: {e}")
            await send(client, room_id, f"❌ Failed to publish: {e}")
            state[room_id] = {"mode": "idle", "data": {}}
        return

    # ── Commands ──────────────────────────────────────────────────────────
    if text.lower() == "!help":
        await send(client, room_id, HELP_TEXT)

    elif text.lower() == "!status":
        await send(client, room_id, f"✅ CMS bot running\nOwner: {OWNER_USER_ID}\nRepo: {GITHUB_REPO} @ {GITHUB_BRANCH}")

    elif text.lower().startswith("!blog "):
        title = text[6:].strip()
        if not title:
            await send(client, room_id, "Usage: `!blog My Post Title`")
            return
        state[room_id] = {"mode": "blog_body", "data": {"title": title}}
        await send(client, room_id, f"📝 Post title: **{title}**\n\nSend the post body as your next message. (Send `!cancel` to abort.)")

    elif text.lower().startswith("!mushroom"):
        parts = text.split(maxsplit=1)
        title = parts[1].strip() if len(parts) > 1 else None
        state[room_id] = {"mode": "mushroom_image", "data": {"title": title}}
        hint = f"title: **{title}**" if title else "no title (will use date)"
        await send(client, room_id, f"🍄 Mushroom photo ({hint})\n\nSend the image as your next message. (Send `!cancel` to abort.)")

    elif text.lower() == "!cancel":
        state[room_id] = {"mode": "idle", "data": {}}
        await send(client, room_id, "❌ Cancelled.")

    else:
        if room_state["mode"] == "idle":
            await send(client, room_id, f"Unknown command. Try `!help`.")

async def on_media(room, event, client: AsyncClient):
    if event.sender == MATRIX_USER_ID:
        return
    if event.sender != OWNER_USER_ID:
        return

    room_id = room.room_id
    room_state = state.get(room_id, {"mode": "idle", "data": {}})

    if room_state["mode"] != "mushroom_image":
        return  # ignore media when not expecting it

    # Get the body text if the user also included a cancel
    url = getattr(event, "url", None) or getattr(event.source.get("content", {}), "url", None)
    if not url:
        url = event.source.get("content", {}).get("url")
    if not url:
        await send(client, room_id, "❌ Could not extract media URL from this message.")
        return

    body = getattr(event, "body", "") or event.source.get("content", {}).get("body", "upload.jpg")
    # Sanitise filename
    ext = body.rsplit(".", 1)[-1].lower() if "." in body else "jpg"
    if ext not in ("jpg", "jpeg", "png", "gif", "webp"):
        ext = "jpg"
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"{timestamp}.{ext}"

    title = room_state["data"].get("title")
    await send(client, room_id, f"⏳ Downloading and uploading **{filename}**…")
    try:
        data = await download_mxc(client, url)
        gh_path = await add_mushroom_photo(data, filename, title, None)
        state[room_id] = {"mode": "idle", "data": {}}
        await send(client, room_id, f"✅ Mushroom photo added!\nFile: `{gh_path}`\nhttps://hackatoa.com/#mycology")
    except Exception as e:
        log.error(f"Mushroom upload failed: {e}")
        await send(client, room_id, f"❌ Upload failed: {e}")
        state[room_id] = {"mode": "idle", "data": {}}

# ── Main ─────────────────────────────────────────────────────────────────────
async def main():
    client = AsyncClient(MATRIX_HOMESERVER, MATRIX_USER_ID)
    client.access_token = MATRIX_TOKEN

    # Confirm whoami
    me = await client.whoami()
    log.info(f"Logged in as {me.user_id}")

    client.add_event_callback(lambda r, e: on_invite(r, e, client), InviteEvent)
    client.add_event_callback(lambda r, e: on_text(r, e, client),   RoomMessageText)
    client.add_event_callback(lambda r, e: on_media(r, e, client),  RoomMessageImage)
    client.add_event_callback(lambda r, e: on_media(r, e, client),  RoomMessageFile)
    client.add_event_callback(lambda r, e: on_media(r, e, client),  RoomMessageVideo)

    log.info("Starting sync loop…")
    await client.sync_forever(timeout=30000, full_state=True)

if __name__ == "__main__":
    asyncio.run(main())
